return {
	-- { "rest-nvim/rest.nvim" },
	--
	-- -- IMPORTANT: need to install this `brew install libpq`
	-- {
	-- 	"kristijanhusak/vim-dadbod-ui",
	-- 	dependencies = {
	-- 		{ "tpope/vim-dadbod", lazy = true },
	-- 		{ "kristijanhusak/vim-dadbod-completion", ft = { "sql", "mysql", "plsql" }, lazy = true }, -- Optional
	-- 	},
	-- 	cmd = {
	-- 		"DBUI",
	-- 		"DBUIToggle",
	-- 		"DBUIAddConnection",
	-- 		"DBUIFindBuffer",
	-- 	},
	-- 	keys = {
	-- 		{ "<leader>e", ":DBUIToggle <CR>", desc = "dbui toggle", silent = true },
	-- 	},
	--
	-- 	init = function()
	-- 		vim.g.db_ui_use_nerd_fonts = 1
	-- 	end,
	-- },
}
