return {
	DefaultFile = "󰈙",
	FileNew = "",
	FileModified = "",
	FileReadOnly = "",
	FolderClosed = "",
	FolderEmpty = "",
	FolderOpen = "",
	Git = "󰊢",
	GitAdd = "",
	GitBranch = "",
	GitChange = "",
	GitConflict = "",
	GitDelete = "",
	GitIgnored = "◌",
	GitRenamed = "➜",
	GitSign = "▎",
	GitStaged = "✓",
	GitUnstaged = "✗",
	GitUntracked = "★",
}
